# Generated by Django 5.0.1 on 2025-12-06 10:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_input', models.CharField(help_text='User input topic for content generation', max_length=500)),
                ('content', models.JSONField(help_text='Generated content (titles, description, tags) in JSON format')),
                ('thumbnail_url', models.URLField(blank=True, help_text='Optional thumbnail URL', max_length=500, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, help_text='Timestamp when content was generated')),
                ('user', models.ForeignKey(help_text='User who generated this content', on_delete=django.db.models.deletion.CASCADE, related_name='ai_contents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Content',
                'verbose_name_plural': 'AI Contents',
                'db_table': 'ai_content',
                'ordering': ['-created_on'],
                'indexes': [models.Index(fields=['-created_on'], name='ai_content_created_5387a1_idx'), models.Index(fields=['user', '-created_on'], name='ai_content_user_id_9f1b01_idx')],
            },
        ),
    ]
