# Generated by Django 5.0.1 on 2025-12-06 10:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Thumbnail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_input', models.CharField(help_text='User input text/description for thumbnail generation', max_length=500)),
                ('thumbnail_url', models.URLField(help_text='ImageKit URL of the generated thumbnail', max_length=1000)),
                ('ref_image', models.URLField(blank=True, help_text='Reference image URL if provided', max_length=500, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, help_text='Timestamp when thumbnail was generated')),
                ('user', models.ForeignKey(help_text='User who generated this thumbnail', on_delete=django.db.models.deletion.CASCADE, related_name='thumbnails', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Thumbnail',
                'verbose_name_plural': 'Thumbnails',
                'db_table': 'thumbnails',
                'ordering': ['-created_on'],
                'indexes': [models.Index(fields=['-created_on'], name='thumbnails_created_b4146e_idx'), models.Index(fields=['user', '-created_on'], name='thumbnails_user_id_3ae3a5_idx')],
            },
        ),
    ]
